# example of a minimal compose file to run tg-spam
services:
  tg-spam:
    image: umputun/tg-spam:master # use :latest tag for production
    hostname: tg-spam
    restart: always
    container_name: tg-spam
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    environment:
      - TELEGRAM_TOKEN
      - TELEGRAM_GROUP
      - FILES_DYNAMIC=/srv/dynamic
    volumes:
      - var/tg-spam:/srv/dynamic # mount volume to store dynamic files