site_name: TG-Spam
site_url: https://tgspam.umputun.dev/
site_author: Umputun
site_description: >-
  TG-Spam is a self-hosted, anti-spam bot for the telegram.

repo_name: umputun/tg-spam
repo_url: https://github.com/umputun/tg-spam
copyright: Some rights reserved &copy; 2023 Umputun

theme:
  name: material
  custom_dir: overrides
  favicon: favicon.png
  language: en
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue grey
  features:
    - navigation.instant
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - navigation.sections
  logo: icon.png

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - minify:
      minify_html: true

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/umputun
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/umputun/tg-spam/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/umputun
  analytics:
    provider: custom
    analytic_id: 04942b40-0a7a-47a1-9dbc-76eb9a9e7999

markdown_extensions:
  - smarty
  - sane_lists
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - TG-SPAM: index.md